name: Partial Regression Tests
run-name: ${{ github.event.schedule && format('Scheduled run at:{0}', github.event.schedule) || format('Manual run, Test Set:{2}, Xray Run ID:{3}, env:{0}, server:{1}', github.event.inputs.env, github.event.inputs.server, github.event.inputs.testSet, github.event.inputs.runID) }}

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment'
        type: choice
        required: true
        options:
          - QA
          - FATE
          - UAT
          - MIG
      server:
        description: 'Server'
        type: choice
        required: true
        options:
          - us
          - de
          - aus
      testObservability:
        description: 'Use BS Test Observability'
        required: true
        type: boolean
        default: true
      xray:
        description: 'Use Jira Xray'
        required: true
        type: boolean
        default: true
      runID:
        description: |
          <<<<< Xray Execution Run ID >>>>>            
          "new/XX-XXX" - new run/existing run
        required: true
        type: string
        default: new
      rc:
        description: Release candidate/Send Slack Message
          true/RC (-gha) number - sends a message (send GHA link)
        required: true
        type: string
        default: false
      testSet:
        description: |
          <<<< Provide a list of Test Sets >>>>
          e.g "Binders, Placeholder, Shortcut, Folders, Members, Permissions, Team, eLog"
        required: true
        type: string
        default: Insert Test Set list

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test_single:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v3
      - name: Inject properties into browserstack.yml
        run: |
          echo "" > browserstack.yml
          echo "userName: ${{ secrets.BS_USER_NAME }}" >> browserstack.yml
          echo "accessKey: ${{ secrets.BS_ACCESS_KEY }}" >> browserstack.yml
          echo "projectName: eConsent Public API" >> browserstack.yml
          echo "buildName: Partial Regression (MR) -- eConsent Public API - ${{ github.event.inputs.env }}_${{ github.event.inputs.server }}" >> browserstack.yml
          echo "framework: testng" >> browserstack.yml
          echo "browserstackAutomation: false" >> browserstack.yml
          echo "testObservability: ${{ github.event.inputs.testObservability }}" >> browserstack.yml
          echo "CUSTOM_TAG_1: Manual Execution" >> browserstack.yml
          echo "CUSTOM_TAG_2: Partial Regression" >> browserstack.yml
          echo "CUSTOM_TAG_3: ${{ github.event.inputs.env }}" >> browserstack.yml 
          echo "CUSTOM_TAG_4: ${{ github.event.inputs.server }}" >> browserstack.yml
          if [[ ${{ github.event.inputs.xray }}  == "true"  ]]; then
          echo "CUSTOM_TAG_5: Xray" >> browserstack.yml
            fi
          cat browserstack.yml
      - name: Inject properties into ghaData.properties
        run: |
          echo "" > src/main/resources/ghaData.properties
          echo "ghaRunId = ${{ github.run_id }}" >> src/main/resources/ghaData.properties
          cat src/main/resources/ghaData.properties          

      - name: Inject Test Set into Partial_Regression_Suite.xml
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>' > src/testNG/Partial_Regression_Suite.xml
          echo '<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">' >> src/testNG/Partial_Regression_Suite.xml
          echo '<suite name="Partial Regression Test Suite - eConsent Public API">' >> src/testNG/Partial_Regression_Suite.xml
          echo '<suite-files>' >> src/testNG/Partial_Regression_Suite.xml

          for test in $(echo ${{ github.event.inputs.testSet }} | tr "," "\n"); do
          echo "<suite-file path=\"Regression/${test}.xml\"/>" >> src/testNG/Partial_Regression_Suite.xml
          done

          echo '</suite-files>' >> src/testNG/Partial_Regression_Suite.xml
          echo '</suite>' >> src/testNG/Partial_Regression_Suite.xml
          cat src/testNG/Partial_Regression_Suite.xml

      - run: docker compose run tests mvn clean test -Dsecret_key=${{ secrets.SECRET_KEY }} -Dsurefire.suiteXmlFiles=src/testNG/Partial_Regression_Suite.xml -Denv=${{ github.event.inputs.env }} -Dserver=${{ github.event.inputs.server }} -DtestRun=testSet -Drc=${{ github.event.inputs.rc }} -Dxray=${{ github.event.inputs.xray }} -DrunID=${{ github.event.inputs.runID }}
      - uses: actions/upload-artifact@v3
        with:
          name: Test Results - ${{ github.event.inputs.env }}_${{ github.event.inputs.server }} - ${{ github.run_number }} - ${{ github.run_id }}
          path: results.txt
      - uses: actions/upload-artifact@v3
        with:
          name: Test Evidence - ${{ github.event.inputs.env }}_${{ github.event.inputs.server }} - ${{ github.run_number }} - ${{ github.run_id }}
          path: evidence.zip